### ISSUE TITLE
Sensor not updating

### ISSUE THREAD

**Issue by ingo916** [tommyjlong/SpeedTest-CLI-With-Home-Assistant#3]
I need some help with this integration. I have followed the instructions and cannot get the sensors to update.
I can execute ./speedtest.bin manually see below.

I added the following to my configuration.yaml

shell_command: #Starting 0.114, command timesout after 60s.
  launch_speedtest_cli: /config/shell_commands/launch_speed_test.sh

calling the service ShellCommand: launch_speedtest_cli, does nothing

==================
./speedtest.bin
   Speedtest by Ookla
      Server: Comcast - Sacramento, CA (id: 9436)
         ISP: Comcast Cable
Idle Latency:     8.50 ms   (jitter: 0.99ms, low: 7.80ms, high: 10.45ms)
    Download:   892.69 Mbps [===\                ] 19%   - latency: 102.72 ms       Download:   892.29 Mbps [====|               ] 20%   - latency: 102.72 ms       Download:   896.40 Mbps [====/               ] 20%   - latency: 102.72 ms       Download:   896.56 Mbps [====-               ] 21%   - latency: 102.72 ms       Download:   896.34 Mbps [====\               ] 22%   - latency: 102.72 ms

**Comment by ingo916** [comment]
I do get this error in the logs not sure if its related

Logger: aiohttp.server
Source: /usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py:405
First occurred: 15:00:33 (3 occurrences)
Last logged: 15:00:33

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"

**Comment by ingo916** [comment]
i entered https for the ha server and should have been http
